# Generated by Django 4.2.17 on 2025-01-14 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0002_req_req'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg.req')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg.shop')),
            ],
        ),
    ]
