# Generated by Django 4.2.17 on 2025-01-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0003_shopreq'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopreq',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
