# Generated by Django 4.2.17 on 2025-01-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0004_shopreq_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status_message_id',
            field=models.CharField(blank=True, max_length=2555, null=True),
        ),
    ]
