# Generated by Django 4.2.17 on 2025-01-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0005_invoice_status_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
