# Generated by Django 4.2.17 on 2025-01-14 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0006_alter_invoice_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='req',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tg.req'),
        ),
    ]
