# Generated by Django 4.2.17 on 2025-01-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0007_invoice_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='check_message_id',
            field=models.CharField(blank=True, max_length=2555, null=True),
        ),
    ]
